[package]
name = "zero_knowledge_solvency"
type = "bin"
authors = ["GROARK", "REB007"]
compiler_version = ">=0.22.0"

[dependencies]
ecrecover = {tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir"}
